import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { useAuth } from "../context/useAuth";
import "./AdminPortal.css";
const API = "http://localhost:5000/api";
async function request(path, token, options = {}) { const response = await fetch(`${API}${path}`, { ...options, headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}`, ...(options.headers || {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.message || "Request failed"); return body; }
const date = (value) => value ? new Date(value).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" }) : "Not specified";
const money = (value) => value === null || value === undefined || value === "" ? "Not specified" : `₹${Number(value).toLocaleString("en-IN")}`;
function Layout({ title, children }) { return <div className="admin-portal"><main className="admin-main"><div className="admin-heading"><p className="eyebrow"><span className="eyebrow-dot" />Platform Administration</p><h1>{title}</h1></div>{children}</main></div>; }
function State({ loading, error, empty, children }) { if (loading) return <div className="admin-state">Loading...</div>; if (error) return <div className="admin-state error"><strong>{error.message}</strong></div>; if (empty) return <div className="admin-state"><strong>{empty}</strong></div>; return children; }
export function AdminDashboardLive() { const { token } = useAuth(); const [stats, setStats] = useState(null); const [error, setError] = useState(null); useEffect(() => { request("/admin/dashboard/stats", token).then((body) => setStats(body.stats)).catch(setError); }, [token]); return <Layout title="Admin dashboard"><State loading={!stats && !error} error={error}><div className="admin-stats">{[["totalStudents", "Total students"], ["totalClients", "Total clients"], ["openGigs", "Open gigs"], ["activeProjects", "Active projects"], ["pendingVerifications", "Pending verifications"], ["openReports", "Open reports"]].map(([key, label]) => <div key={key}><strong>{stats[key]}</strong><span>{label}</span><small>Live database count</small></div>)}</div><div className="admin-grid"><Link className="admin-card shortcut" to="/admin/users"><h2>User management</h2><p>Search users and update account status.</p></Link><Link className="admin-card shortcut" to="/admin/projects"><h2>Project monitoring</h2><p>Review platform projects and participants.</p></Link><Link className="admin-card shortcut" to="/admin/payments"><h2>Payment monitoring</h2><p>View platform payment records.</p></Link></div></State></Layout>; }
export function AdminUsersLive() { const { token } = useAuth(); const [users, setUsers] = useState([]); const [query, setQuery] = useState(""); const [role, setRole] = useState("ALL"); const [loading, setLoading] = useState(true); const [error, setError] = useState(null); const load = () => { setLoading(true); request(role === "ALL" ? "/admin/users" : `/admin/users?role=${role}`, token).then((body) => setUsers(body.users || [])).catch(setError).finally(() => setLoading(false)); }; useEffect(load, [token, role]); const visible = users.filter((user) => `${user.name} ${user.email} ${user.role} ${user.account_status}`.toLowerCase().includes(query.toLowerCase())); const update = async (id, status) => { try { await request(`/admin/users/${id}/status`, token, { method: "PUT", body: JSON.stringify({ status }) }); load(); } catch (err) { setError(err); } }; return <Layout title="Users"><div className="admin-toolbar"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search users" /><select value={role} onChange={(event) => setRole(event.target.value)}><option>ALL</option><option>STUDENT</option><option>CLIENT</option></select></div><State loading={loading} error={error} empty={visible.length === 0 ? "No users match this filter." : null}><div className="stack">{visible.map((user) => <article className="admin-card report-row" key={user.user_id}><div><div className="admin-kicker">{user.role}<span>{user.account_status}</span></div><h2>{user.name}</h2><p>{user.email} · Joined {date(user.created_at)}</p><small>{user.company_name || user.college_name || "No profile detail"}</small></div><div className="admin-actions"><select value={user.account_status} disabled={user.role === "ADMIN"} onChange={(event) => update(user.user_id, event.target.value)}><option>ACTIVE</option><option>INACTIVE</option><option>SUSPENDED</option></select></div></article>)}</div></State></Layout>; }
export function AdminProjectsLive() { const { token } = useAuth(); const [items, setItems] = useState([]); const [error, setError] = useState(null); useEffect(() => { request("/admin/projects", token).then((body) => setItems(body.projects || [])).catch(setError); }, [token]); return <Layout title="Project monitoring"><State loading={!items.length && !error} error={error} empty={!items.length ? "No projects found." : null}><div className="admin-grid">{items.map((item) => <article className="admin-card" key={item.project_id}><div className="admin-kicker">{item.project_status}<span>{item.project_id}</span></div><h2>{item.project_title}</h2><p>Client: {item.client_name} · Student: {item.student_name}</p><div className="admin-meta"><span>{date(item.start_date)} - {date(item.expected_end_date)}</span><strong>{money(item.agreed_amount)}</strong></div></article>)}</div></State></Layout>; }
export function AdminPaymentsLive() { const { token } = useAuth(); const [items, setItems] = useState([]); const [error, setError] = useState(null); useEffect(() => { request("/admin/payments", token).then((body) => setItems(body.payments || [])).catch(setError); }, [token]); return <Layout title="Payment monitoring"><State loading={!items.length && !error} error={error} empty={!items.length ? "No payments found." : null}><div className="stack">{items.map((item) => <article className="admin-card report-row" key={item.payment_id}><div><div className="admin-kicker">{item.payment_status}<span>{date(item.payment_date)}</span></div><h2>{money(item.amount)}</h2><p>{item.project_title} · Client {item.client_name} · Student {item.student_name}</p></div><small>{item.payment_method || "No payment method"}</small></article>)}</div></State></Layout>; }
export function AdminProfileLive() { const { token } = useAuth(); const [form, setForm] = useState({}); const [loading, setLoading] = useState(true); const [error, setError] = useState(null); const [notice, setNotice] = useState(""); useEffect(() => { request("/admin/profile", token).then((body) => setForm(body.profile)).catch(setError).finally(() => setLoading(false)); }, [token]); const save = async (event) => { event.preventDefault(); try { await request("/admin/profile", token, { method: "PUT", body: JSON.stringify({ name: form.name, phone: form.phone, profilePicture: form.profile_picture }) }); setNotice("Profile updated successfully."); } catch (err) { setError(err); } }; return <Layout title="Admin profile"><State loading={loading} error={error}><div className="admin-card form-card">{notice && <div className="admin-notice">{notice}</div>}<form onSubmit={save}><label>Name<input required value={form.name || ""} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>Email<input disabled value={form.email || ""} /></label><label>Phone<input value={form.phone || ""} onChange={(event) => setForm({ ...form, phone: event.target.value })} /></label><button className="admin-button">Save profile</button></form></div></State></Layout>; }
