import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { useAuth } from "../context/useAuth";
import "./PortalExtras.css";

const API = "http://localhost:5000/api";
async function request(path, token, options = {}) { const response = await fetch(`${API}${path}`, { ...options, headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}`, ...(options.headers || {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.message || "Request failed"); return body; }
const date = (value) => value ? new Date(value).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" }) : "Not specified";
const messageOf = (error) => error?.message || "Something went wrong. Please try again.";
function State({ loading, error, empty, children }) { if (loading) return <div className="extra-state">Loading...</div>; if (error) return <div className="extra-state error"><strong>{messageOf(error)}</strong></div>; if (empty) return <div className="extra-state"><strong>Nothing here yet</strong><span>{empty}</span></div>; return children; }
function Notice({ children, error = false }) { return children ? <div className={`extra-notice${error ? " error" : ""}`}>{children}</div> : null; }
function Shell({ role, title, children }) { const links = role === "STUDENT" ? [["/student/dashboard", "Dashboard"], ["/student/projects", "Projects"], ["/student/reports", "Reports"], ["/student/reviews", "Reviews"], ["/student/profile", "Profile"]] : [["/client/dashboard", "Dashboard"], ["/client/projects", "Projects"], ["/client/reports", "Reports"], ["/client/reviews", "Reviews"], ["/client/profile", "Profile"]]; return <div className={`extras ${role.toLowerCase()}`}><header><Link to={links[0][0]} className="extras-logo"><span className="logo-mark">V</span>VerifiedGigs</Link><nav>{links.map(([to, label]) => <Link key={to} to={to}>{label}</Link>)}</nav></header><main><p className="eyebrow"><span className="eyebrow-dot" />{role === "STUDENT" ? "Student Portal" : "Client Portal"}</p><h1>{title}</h1>{children}</main></div>; }
function ReportForm({ role, projects, gigs, onSaved }) { const { token } = useAuth(); const [target, setTarget] = useState(""); const [reason, setReason] = useState(""); const [description, setDescription] = useState(""); const [notice, setNotice] = useState(""); const [error, setError] = useState(null); const submit = async (event) => { event.preventDefault(); setError(null); setNotice(""); if (!target || !reason.trim()) return setError(new Error("Choose a target and enter a reason.")); const [type, id] = target.split(":"); const body = { reason: reason.trim(), description: description.trim() }; body[type === "project" ? "projectId" : type === "gig" ? "gigId" : "reportedUserId"] = Number(id); try { await request("/reports", token, { method: "POST", body: JSON.stringify(body) }); setNotice("Report submitted successfully."); setTarget(""); setReason(""); setDescription(""); onSaved(); } catch (err) { setError(err); } }; return <section className="extra-card"><h2>Submit a report</h2>{notice && <Notice>{notice}</Notice>}{error && <Notice error>{messageOf(error)}</Notice>}<form onSubmit={submit}><label>Target<select required value={target} onChange={(event) => setTarget(event.target.value)}><option value="">Choose a project or gig</option>{projects.map((project) => <option key={`project:${project.project_id}`} value={`project:${project.project_id}`}>Project: {project.project_title || project.gig_title}</option>)}{gigs.map((gig) => <option key={`gig:${gig.gig_id}`} value={`gig:${gig.gig_id}`}>Gig: {gig.title}</option>)}</select></label><label>Reason<input required value={reason} onChange={(event) => setReason(event.target.value)} /></label><label>Description<textarea value={description} onChange={(event) => setDescription(event.target.value)} /></label><button type="submit">Submit report</button></form></section>; }
export function PortalReports({ role }) { const { token } = useAuth(); const [reports, setReports] = useState([]); const [projects, setProjects] = useState([]); const [gigs, setGigs] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(null); const load = () => { setLoading(true); const projectPath = role === "STUDENT" ? "/student/projects" : "/client/projects"; const gigPath = role === "STUDENT" ? "/gigs" : "/client/gigs"; Promise.all([request("/reports/my", token), request(projectPath, token), request(gigPath, token)]).then(([reportBody, projectBody, gigBody]) => { setReports(reportBody.reports || []); setProjects(projectBody.projects || []); setGigs(gigBody.gigs || []) }).catch(setError).finally(() => setLoading(false)); }; useEffect(load, [token, role]); return <Shell role={role} title="Reports and issues"><State loading={loading} error={error}><ReportForm role={role} projects={projects} gigs={gigs} onSaved={load} /><section className="extra-card"><h2>My reports</h2>{reports.length === 0 ? <p className="muted">You have not submitted any reports.</p> : <div className="extra-list">{reports.map((report) => <article key={report.report_id}><strong>{report.reason}</strong><span>{report.report_status}</span><small>{date(report.reported_at)}</small><p>{report.description || "No description provided."}</p></article>)}</div>}</section></State></Shell>; }
function ReviewForm({ project, reviewedUserId, onSaved }) { const { token } = useAuth(); const [rating, setRating] = useState(""); const [reviewText, setReviewText] = useState(""); const [error, setError] = useState(null); const [notice, setNotice] = useState(""); const submit = async (event) => { event.preventDefault(); try { await request(`/projects/${project.project_id}/reviews`, token, { method: "POST", body: JSON.stringify({ reviewedUserId, rating: Number(rating), reviewText }) }); setNotice("Review submitted."); setRating(""); setReviewText(""); onSaved(); } catch (err) { setError(err); } }; return <form className="review-form" onSubmit={submit}>{notice && <Notice>{notice}</Notice>}{error && <Notice error>{messageOf(error)}</Notice>}<label>Rating<select required value={rating} onChange={(event) => setRating(event.target.value)}><option value="">Choose 1-5</option><option>1</option><option>2</option><option>3</option><option>4</option><option>5</option></select></label><label>Review<textarea value={reviewText} onChange={(event) => setReviewText(event.target.value)} /></label><button type="submit">Submit review</button></form>; }
export function PortalReviews({ role }) { const { token, user } = useAuth(); const [projects, setProjects] = useState([]); const [reviews, setReviews] = useState({}); const [loading, setLoading] = useState(true); const [error, setError] = useState(null); const load = async () => { setLoading(true); try { const body = await request(role === "STUDENT" ? "/student/projects" : "/client/projects", token); const list = body.projects || []; setProjects(list.filter((project) => project.project_status === "COMPLETED")); const entries = await Promise.all(list.map(async (project) => [project.project_id, (await request(`/projects/${project.project_id}/reviews`, token)).reviews || []])); setReviews(Object.fromEntries(entries)); } catch (err) { setError(err); } finally { setLoading(false); } }; useEffect(() => { load(); }, [token, role]); return <Shell role={role} title="Project reviews"><State loading={loading} error={error} empty={projects.length === 0 ? "Completed projects eligible for reviews will appear here." : null}><div className="extra-list">{projects.map((project) => { const reviewedUserId = role === "STUDENT" ? project.client_user_id : project.student_user_id; return <article className="extra-card" key={project.project_id}><h2>{project.project_title || project.gig_title}</h2><p>Completed project with {role === "STUDENT" ? project.client_name : project.student_name}.</p>{(reviews[project.project_id] || []).map((review) => <div className="review" key={review.review_id}><strong>{review.rating}/5</strong><span>{review.review_text || "No written review"}</span></div>)}{reviewedUserId ? <ReviewForm project={project} reviewedUserId={reviewedUserId} onSaved={load} /> : <Notice error>Participant details are unavailable for this project.</Notice>}</article>; })}</div></State></Shell>; }
export function StudentReports() { return <PortalReports role="STUDENT" />; }
export function StudentReviews() { return <PortalReviews role="STUDENT" />; }
export function ClientReports() { return <PortalReports role="CLIENT" />; }
export function ClientReviews() { return <PortalReviews role="CLIENT" />; }
